name: CI-build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  workflow_dispatch:

env:
  GITHUB_ACTIONS: true

jobs:
  CI:
    strategy:
      matrix:
        python-version: ["3.10"]
        os-version: ["windows-latest", "ubuntu-20.04", "macos-13", "macos-14"]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
        continue-on-error: true

      - name: vulkan dll
        if: matrix.os-version == 'windows-latest'
        run: echo F | xcopy .\assets\vulkan-1.dll C:\Windows\System32

      - name: Build
        run: |
          pdm install
          pdm run pyinstaller

      - name: zip-windows
        if: matrix.os-version == 'windows-latest'
        run: |
          cd dist\Final2x-core
          7z a -r Final2x-core-${{ matrix.os-version }}.zip *

      - name: zip-linux
        if: matrix.os-version == 'ubuntu-20.04'
        run: |
          cd dist/Final2x-core
          zip -9 -r Final2x-core-${{ matrix.os-version }}.zip ./*

      - name: zip-macos-x64
        if: matrix.os-version == 'macos-13'
        run: |
          cd dist/Final2x-core
          zip -9 -r Final2x-core-macos-x64.zip ./*

      - name: zip-macos-arm64
        if: matrix.os-version == 'macos-14'
        run: |
          cd dist/Final2x-core
          zip -9 -r Final2x-core-macos-arm64.zip ./*

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-core-${{ matrix.os-version }}
          path: dist/Final2x-core/*.zip

      - name: Test-windows
        if: matrix.os-version == 'windows-latest'
        run: |
          cd dist\Final2x-core
          .\Final2x-core

      - name: Test-unix
        if: matrix.os-version != 'windows-latest'
        run: |
          cd dist/Final2x-core
          ./Final2x-core
