name: pip-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  PIP-test:
    strategy:
      matrix:
        python-version: [ "3.9" ]
        os-version: [ "windows-latest" , "ubuntu-20.04" , "macos-latest" ]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: vulkan dll
        if: matrix.os-version == 'windows-latest'
        run: echo F | xcopy .\assets\vulkan-1.dll C:\Windows\System32

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Final2x-core pathlib

      - name: Test pip
        run: |
          cd tests
          python CIsetconfig.py
          python CItestpip.py
