name: pip-test

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  workflow_dispatch:

env:
  GITHUB_ACTIONS: true

jobs:
  pip-test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os-version: ["windows-latest", "ubuntu-20.04", "macos-13", "macos-14"]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
        continue-on-error: true

      - name: vulkan dll
        if: matrix.os-version == 'windows-latest'
        run: echo F | xcopy .\assets\vulkan-1.dll C:\Windows\System32

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Final2x-core

      - name: Test pip
        run: |
          cd scripts
          python gen_config.py
          python CItestpip.py
