name: Release-pypi

on:
  workflow_dispatch:

env:
  GITHUB_ACTIONS: true

jobs:
  Pypi:
    strategy:
      matrix:
        python-version: ["3.10"]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pdm-project/setup-pdm@v4
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
        continue-on-error: true

      - name: Check Python version
        run: |
          python --version

      - name: Build package
        run: |
          pdm install --skip download_models
          pdm build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API }}
